import ProjectDescription

let clientName = Template.Attribute.required("name")

private let template = Template(
    description: "A Client Template",
    attributes: [clientName],
    items: [
        .file(
            path: "Projects/Client/\(clientName)Client/Project.swift",
            templatePath: "Client.stencil"
        ),
        .string(
            path: "Projects/Client/\(clientName)Client/Sources/Source.swift",
            contents: "// Autogenerated by Tuist"
        ),
        .string(
            path: "Projects/Client/\(clientName)Client/Tests/Sources/Source.swift",
            contents: "// Autogenerated by Tuist"
        )
    ]
)
