import ProjectDescription

let domainName = Template.Attribute.required("name")

private let template = Template(
    description: "A Domain Template",
    attributes: [domainName],
    items: [
        .file(
            path: "Projects/Domain/\(domainName)Domain/Project.swift",
            templatePath: "Domain.stencil"
        ),
        .string(
            path: "Projects/Domain/\(domainName)Domain/Sources/Source.swift",
            contents: "// Autogenerated by Tuist"
        ),
        .string(
            path: "Projects/Domain/\(domainName)Domain/Tests/Sources/Source.swift",
            contents: "// Autogenerated by Tuist"
        )
    ]
)
