import ProjectDescription

private let moduleName = Template.Attribute.required("name")

private let template = Template(
    description: "A template for a new dynamic framework",
    attributes: [
        moduleName
    ],
    items: [
        .file(
            path: "Projects/Core/\(moduleName)/Project.swift",
            templatePath: "Core.stencil"
        ),
        .string(
            path: "Projects/Core/\(moduleName)/Sources/Source.swift",
            contents: "// Autogenerated by Tuist"
        ),
        .string(
            path: "Projects/Core/\(moduleName)/Resources/dummy.txt",
            contents: "dummy file"
        )
    ]
)
